### ISSUE TITLE
Visualiser les transects

### ISSUE THREAD

**Issue by orovellotti** [PnX-SI/gn_module_monitoring_habitat_station#5]
Au niveau plus grand niveau de zoom les transects doivent etre représentés comme des points.

Voir comment utiliser le plugin Deflate 👍 
https://github.com/oliverroick/Leaflet.Deflate

**Comment by camillemonchicourt** [comment]
Duplicate - https://github.com/PnX-SI/gn_module_suivi_habitat_station/issues/4
